import React, { useEffect, useState } from 'react'
import { useAuth } from '../context/AuthContext.jsx'
import { aiService } from '../services/apiService.js'

const agentIcon  = { spending:'ti-trending-down', savings:'ti-piggy-bank', loan:'ti-building-bank', bill_reminder:'ti-receipt', investment:'ti-chart-line' }
const agentColor = { spending:['#431f05','#fcd34d'], savings:['#14432a','#86efac'], loan:['#1e3a5f','#93c5fd'], bill_reminder:['#3f1212','#fca5a5'], investment:['#2e1f5e','#c4b5fd'] }
const badgeClass = { spending:'badge-warning', savings:'badge-success', loan:'badge-info', bill_reminder:'badge-danger', investment:'badge-purple' }

export default function Recommendations() {
  const { token } = useAuth()
  const [recs, setRecs]   = useState([])
  const [loading, setLoading] = useState(true)
  const [running, setRunning] = useState(false)

  const load = () => {
    aiService.getRecommendations(token)
      .then(d => setRecs(d.data?.length ? d.data : demoRecs))
      .catch(() => setRecs(demoRecs))
      .finally(() => setLoading(false))
  }

  useEffect(load, [token])

  const triggerRun = async () => {
    setRunning(true)
    try { await aiService.triggerRun(token); load() }
    catch(e) { console.error(e) }
    finally { setRunning(false) }
  }

  return (
    <div>
      <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between', marginBottom:16 }}>
        <h2 style={{ fontSize:18, fontWeight:500 }}>Recommendations</h2>
        <button onClick={triggerRun} disabled={running} style={{ fontSize:12, padding:'8px 14px' }}>
          {running ? 'Running agents…' : '⚡ Run agents now'}
        </button>
      </div>
      <p style={{ fontSize:13, color:'#8b9ab5', marginBottom:16 }}>Personalised suggestions generated by your AI agents.</p>
      <div style={{ display:'flex', flexDirection:'column', gap:10 }}>
        {recs.map((rec, i) => {
          const [bg, fg] = agentColor[rec.agent_type] || ['#1c2333','#93c5fd']
          return (
            <div key={i} className="card" style={{ display:'flex', gap:12, alignItems:'flex-start' }}>
              <div style={{ width:34, height:34, borderRadius:8, background:bg, color:fg, display:'flex', alignItems:'center', justifyContent:'center', fontSize:16, flexShrink:0 }}>
                <i className={`ti ${agentIcon[rec.agent_type]||'ti-bulb'}`} />
              </div>
              <div style={{ flex:1 }}>
                <div style={{ fontSize:13, fontWeight:500, color:'#e8edf5', marginBottom:3 }}>{rec.title}</div>
                <div style={{ fontSize:12, color:'#8b9ab5', lineHeight:1.55 }}>{rec.description}</div>
                <div style={{ display:'flex', alignItems:'center', gap:8, marginTop:8 }}>
                  <span className={`badge ${badgeClass[rec.agent_type]||'badge-info'}`}>{rec.agent_type?.replace('_',' ')}</span>
                  {rec.potential_value && <span style={{ fontSize:11, color:'#566480', marginLeft:'auto' }}>Potential: ₹{parseFloat(rec.potential_value).toLocaleString()}</span>}
                  <span className={`badge ${rec.priority==='urgent'?'badge-danger':rec.priority==='high'?'badge-warning':'badge-info'}`}>{rec.priority}</span>
                </div>
              </div>
            </div>
          )
        })}
      </div>
    </div>
  )
}

const demoRecs = [
  { agent_type:'spending',    title:'Reduce food delivery spend',      description:'You spent ₹4,800 on Swiggy/Zomato in June — 12% of total spend. Cooking 3 extra meals a week could save ₹1,500/month.', priority:'medium', potential_value:1500 },
  { agent_type:'savings',     title:'Start SIP of ₹5,000/month',       description:'Based on surplus income, a ₹5,000 monthly SIP in a balanced mutual fund could grow to ₹8.7L in 10 years at 12% CAGR.', priority:'medium', potential_value:870000 },
  { agent_type:'loan',        title:'Pre-approved home loan — ₹35L',   description:'Your credit score of 768 qualifies you for a home loan at 8.4% p.a. EMI would be ₹30,200/month over 20 years.', priority:'medium', potential_value:3500000 },
  { agent_type:'bill_reminder', title:'BESCOM bill due in 3 days',     description:'Your electricity bill of ₹1,840 is due on 23 June. Enable auto-pay to avoid late fees and earn 1% cashback.', priority:'urgent', potential_value:null },
  { agent_type:'investment',  title:'Open an FD with surplus cash',    description:'You have ₹45,000 idle in your savings account. A 1-year SBI FD at 6.8% p.a. would earn ₹3,060 interest.', priority:'low', potential_value:3060 },
]